epidemic_notifier/routes.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
# __author__ = "Albin TCHOPBA"
# __copyright__ = "Copyright 2020 Albin TCHOPBA and contributors"
# __credits__ = ["Albin TCHOPBA and contributors"]
# __license__ = "GPL"
# __version__ = "3"
# __maintainer__ = "Albin TCHOPBA"
# __email__ = "Albin TCHOPBA <atchopba @ gmail dot com"
# __status__ = "Production"

from flask import Blueprint, render_template, redirect, url_for, request, make_response
from flask_login import login_required, logout_user, current_user

from .core.db.db import DB
from .core.db.personne import Personne, TPersonne
from .core.db.relation import Relation
from .core.db.contact_relation_personne import CRP, TCRP
from .core.db.test import Test, TTest
from .core.db.test_type import TestType
from .core.db.test_lieu import TestLieu
from .core.db.notification import Notification
from .core.db.type_consultation import TConsultation
from .core.db.personne_consultation import PConsultation, TPConsultation
from .core.db.personne_vie_condition import TPVCondition, PVCondition
from .core.db.personne_diagnostic import PDiagnostic, TPDiagnostic
from .core.db.personne_guerison import PGuerison, TPGuerison
from .core.db.guerison_type import GuerisonType
from .core.db.symptome import Symptome
from .core.db.personne_notification import PNotification
from .core.db.user_historique import UserHistorique, TUserHistorique
from .core import notifier as notifier
from .core.personne_graph import build_graph
from .core import common as cm
from config import Config
import json

# Blueprint Configuration
main_bp = Blueprint('main_bp', 
                    __name__,
                    template_folder='templates',
                    static_folder='static')

DEFAULT_OUI = "oui"
DEFAULT_NON = "non"

@main_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth_bp.login'))

@main_bp.route("/")
@login_required
def home():
    cpersonne_ = cm.CPersonne(Personne().get_count(), Personne().get_count_gueri(), Personne().get_count_suspect())
    ctest_ = cm.CTest(Test().get_count(), Test().get_count_positif(), Test().get_count_negatif())
    return render_template("myapp/index.html", cpersonne=cpersonne_, ctest=ctest_)

@main_bp.route("/db")
@login_required
def db_home():
    return render_template("myapp/db.html")

@main_bp.route("/db", methods=["POST"])
@login_required
def db_create():
    DB().create_db()
    return redirect("/personnes")

@main_bp.route("/personnes")
@login_required
def home_personne():
    personnes = CRP().get_personnes_crp() #Personne().get_all() #
    #
    tuh = TUserHistorique(current_user.id, None, Personne.ACTION_LIST, cm.get_current_date_fr(), cm.get_current_time())
    UserHistorique().add(tuh)
    return render_template("myapp/personne.html", personnes=personnes, nb_personnes=len(personnes))

def param_and_add_personne(request):
    nom = request.form["nom"]
    prenom = request.form["prenom"]
    date_naiss = request.form["date_naiss"]
    num_telephone = request.form["num_telephone"]
    email = request.form["email"]
    personne = TPersonne(nom, prenom, date_naiss, num_telephone, email)
    return Personne().add(personne)
    
@main_bp.route("/personnes", methods=["POST"])
@login_required
def add_personne():
    personne_id = param_and_add_personne(request)
    if personne_id is not None:
        #
        tuh = TUserHistorique(current_user.id, personne_id, Personne.ACTION_INSERT, cm.get_current_date_fr(), cm.get_current_time())
        UserHistorique().add(tuh)
        return redirect("/personnes")
    return render_template("myapp/personne.html", error=Config.ERROR_MSG_INSERT)

@main_bp.route("/personnes/delete/<int:personne_id>")
@login_required
def delete_personne(personne_id):
    Personne().delete(personne_id)
    CRP().delete_due_2_personne(personne_id)
    #
    tuh = TUserHistorique(current_user.id, personne_id, Personne.ACTION_DELETE, cm.get_current_date_fr(), cm.get_current_time())
    UserHistorique().add(tuh)
    return redirect("/personnes")

@main_bp.route("/personnes/graph")
@login_required
def graph_personne():
    # selection des personnes pour construire le graphe
    p_ = Personne().get_all()
    graph_msg = "Aucune personne enregistrée pour tracer le graphe!" if len(p_) == 0 else ""
    build_graph()
    return render_template("myapp/personne-graph.html", graph_msg=graph_msg)

@main_bp.route("/personnes/search", methods=["POST"])
@login_required
def search_personne():
    p_name = request.form["search_name"]
    personne_id_1 = request.form["personne_id_1"]
    json_ = json.dumps(Personne().find_by_name_in_crp(personne_id_1, p_name))
    resp = make_response(json_)
    resp.status_code = 200
    resp.headers["Access-Control-Allow-Origin"] = '*'
    return resp

@main_bp.route("/personnes/guerison", methods=["GET"])
@login_required
def guerison_personne():
    personne = Personne().get_one(request.args.get("personne"))
    guerison_types = GuerisonType().get_all()
    #
    tuh = TUserHistorique(current_user.id, None, PGuerison.ACTION_LIST, cm.get_current_date_fr(), cm.get_current_time())
    UserHistorique().add(tuh)
    return render_template("myapp/personne_guerison.html", 
                           personne=personne,
                           date_guerison=cm.get_current_date_fr(),
                           guerison_types=guerison_types,
                           pguerisons=PGuerison().get_all())

@main_bp.route("/personnes/guerison", methods=["POST"])
@login_required
def set_guerison_personne():
    personne_id = request.form["personne_id"]
    guerison_type_id = request.form["guerison_type_id"]
    date_guerison = request.form["date_guerison"]
    has_been_isole = get_request_checkbox_value(request, "has_been_isole")
    has_been_sous_oxygene = get_request_checkbox_value(request, "has_been_sous_oxygene")
    has_been_sous_antibiotique = get_request_checkbox_value(request, "has_been_sous_antibiotique")
    has_been_hospitalise = get_request_checkbox_value(request, "has_been_hospitalise")
    has_scanner_controle = get_request_checkbox_value(request, "has_scanner_controle")
    personne_guerison_id = PGuerison().add(TPGuerison(personne_id, guerison_type_id, date_guerison, has_been_isole, has_been_sous_oxygene, has_been_sous_antibiotique, has_been_hospitalise, has_scanner_controle, cm.get_current_datetime_fr()))
    if personne_guerison_id:
        #
        tuh = TUserHistorique(current_user.id, personne_id, PGuerison.ACTION_INSERT, cm.get_current_date_fr(), cm.get_current_time())
        UserHistorique().add(tuh)
        return redirect("/tests")
    return render_template("/personne/guerison?personne="+ personne_id, error=Config.ERROR_MSG_INSERT)

@main_bp.route("/personnes/consultation", methods=["GET"])
@login_required
def consultation_personne():
    personne_id = request.args.get("personne")
    personne = Personne().get_one(personne_id)
    type_consultations = TConsultation().get_all()
    pconsultations = PConsultation().get_by_personne_id(personne_id)
    #
    tuh = TUserHistorique(current_user.id, personne_id, PConsultation.ACTION_LIST, cm.get_current_date_fr(), cm.get_current_time())
    UserHistorique().add(tuh)
    return render_template("myapp/personne_consultation.html", 
                           personne=personne, 
                           type_consultations=type_consultations, 
                           date_consultation=cm.get_current_date_fr(), 
                           heure_consultation=cm.get_current_time(),
                           pconsultations=pconsultations)

@main_bp.route("/personnes/consultation", methods=["POST"])
@login_required
def add_consultation_personne():
    personne_id = request.form["personne_id"]
    type_consultation_id = request.form["type_consultation_id"]
    date_consultation = request.form["date_consultation"]
    heure_consultation = request.form["heure_consultation"]
    pconsultation_id = PConsultation().add(TPConsultation(type_consultation_id, personne_id, date_consultation, heure_consultation, cm.get_current_datetime_fr()))
    if pconsultation_id :
        #
        tuh = TUserHistorique(current_user.id, personne_id, PConsultation.ACTION_INSERT, cm.get_current_date_fr(), cm.get_current_time())
        UserHistorique().add(tuh)
        return redirect("/personnes/consultation?personne="+personne_id)
    return render_template("/personnes/consultation?personne="+ personne_id, error=Config.ERROR_MSG_INSERT)

@main_bp.route("/personnes/consultation/delete/<int:consultation_id>")
@login_required
def delete_consultation_personne(consultation_id):
    PConsultation().delete(consultation_id)
    personne_id = request.args.get("personne")
    #
    tuh = TUserHistorique(current_user.id, personne_id, PConsultation.ACTION_DELETE, cm.get_current_date_fr(), cm.get_current_time())
    UserHistorique().add(tuh)
    return redirect("/personnes/consultation/"+ str(personne_id))

@main_bp.route("/personnes/diagnostic", methods=["GET"])
@login_required
def diagnostic_personne():
    personne_id = request.args.get("personne")
    personne = Personne().get_one(personne_id)
    symptomes = Symptome().get_all()
    pdiagnostics = PDiagnostic().get_by_personne_id(personne_id)
    #
    tuh = TUserHistorique(current_user.id, personne_id, PDiagnostic.ACTION_LIST, cm.get_current_date_fr(), cm.get_current_time())
    UserHistorique().add(tuh)
    return render_template("myapp/personne_diagnostic.html", 
                           personne=personne, 
                           symptomes=symptomes,
                           suspect_score_min=Config.SUSPECT_SCORE_MIN,
                           date_debut=cm.get_current_date_fr(),
                           pdiagnostics=pdiagnostics)

def get_symptome_from_request(request_dict, index_):
    try: 
        symptome = request_dict[index_] 
    except: 
        symptome = None
    return symptome

@main_bp.route("/personnes/diagnostic", methods=["POST"])
@login_required

epidemic_notifier/templates/inc/form_personne.html
<div class="label-row"><i>Personne : </i></div>

<div class="form-row">
  <div class="name">Nom : </div>
  <div class="value">
    <input class="input--style-6" type="text" id="nom" name="nom" value="" placeholder="Nom de la personne" size="32" autocomplete="false">
  </div>
</div>

<div class="form-row">
  <div class="name">Prenom : </div>
  <div class="value">
    <input  class="input--style-6" type="text" id="prenom" name="prenom" value="" placeholder="Prenom de la personne" size="32" autocomplete="false">
  </div>
</div>

<div class="form-row">
  <div class="name">Date de naissance : </div>
  <div class="value">
    <input  class="input--style-6" type="text" id="date_naiss" name="date_naiss" value="" placeholder="01/01/1971" autocomplete="false">
  </div>
</div>

<div class="form-row">
  <div class="name">Num. de telephone : </div>
  <div class="value">
    <input  class="input--style-6" type="text" id="num_telephone" name="num_telephone" value="" placeholder="+237 6 97 69 64 97" autocomplete="false">
  </div>
</div>

<div class="form-row">
  <div class="name">@mail : </div>
  <div class="value">
    <input  class="input--style-6" type="text" id="email" name="email" value="" placeholder="personne@personne.com" size="32" autocomplete="false">
  </div>
</div>

epidemic_notifier/templates/inc/header.html
    <title>Epidemic-notifier</title>
    <!-- En-tête du document  -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
   
    <!-- Balise meta  -->
    <meta name="title" content="Titre de la page" />
    <meta name="description" content="description de la page" />
    <meta name="keywords" content="mots-clé1, mots-clé2, ..." />
   
    <!-- Indexer et suivre -->
    <meta name="robots" content="index,follow" />
   
    <!--  Relier une feuille CSS externe  -->
    <!-- <link rel='stylesheet' href='votre-fichier.css' type='text/css' /> -->
   
    <!-- Incorporez du CSS dans la page  -->
    <style type="text/css" media="screen">
      
    </style>

    <!-- Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- jQuery UI -->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Main CSS-->
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet" media="all">

    <script type="text/javascript" src="{{ url_for('static', filename='js/site.js') }}"></script>

epidemic_notifier/templates/inc/header_menu.html
<h3>Bienvenue sur Epidemic notifier</h3>
    <div>
		<a href="/">Accueil</a>&nbsp;&nbsp;
        <a href="/db">Database</a>&nbsp;&nbsp;
        <!-- <a href="/relations">Relations</a>&nbsp;&nbsp; -->
        <a href="/personnes">Personnes</a>&nbsp;&nbsp;
        <a href="/personnes/graph">Graphe personnes</a>&nbsp;&nbsp;
        <a href="/tests">Test</a>&nbsp;&nbsp;
        <a href="/notifications">Notifications</a>&nbsp;&nbsp;
        {% if current_user.is_authenticated %}
            <!-- <p>Hi {{ current_user.name }}!</p> -->
            <a href="{{ url_for('main_bp.logout') }}">Me d&eacute;connecter</a>
        {% endif %}
    </div>
    <br/>

epidemic_notifier/templates/inc/list_personne.html
<table width="100%">
  <thead>
    <tr>
      <td>ID</td>
      <td>Nom</td>
      <td>Prénom</td>
      <td>Date de naissance</td>
      <td>Numéro de téléphone</td>
      <td>@mail</td>
      <td>cas suspect?</td>
      <td>Pr&eacute;sente signe?</td>
      <td>NB contact</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    {% if personnes %}
      {% for p in personnes %}
        <tr>
          <td>{{ p.id }}</td>
          <td>{{ p.nom }}</td>
          <td>{{ p.prenom }}</td>
          <td>{{ p.date_naiss }}</td>
          <td>{{ p.num_telephone }}</td>
          <td>{{ p.email }}</td>
          <td>{{ p.suspect }}</td>
          <td>{{ p.presente_signe }}</td>
          <td>{{ p.nb_contact }}</td>
          <td width="34%">
            &nbsp;<a href="/crp?personne={{ p.id }}" title="personnes avec qui un contact a été fait"><img src="{{ url_for('static', filename='icones/contacts.png') }}" /></a>&nbsp;
            &nbsp;<a href="/personnes/consultation?personne={{ p.id }}" title="consultation"><img src="{{ url_for('static', filename='icones/consultation.png') }}" /></a>&nbsp;
            &nbsp;<a href="/personnes/viecondition?personne={{ p.id }}" title="conditions de vie"><img src="{{ url_for('static', filename='icones/cond-vie.png') }}" /></a>&nbsp;
            &nbsp;<a href="/personnes/diagnostic?personne={{ p.id }}" title="diagnostic"><img src="{{ url_for('static', filename='icones/diagnostic.png') }}" /></a>&nbsp;
            &nbsp;<a href="/tests?personne={{ p.id }}" title="test"><img src="{{ url_for('static', filename='icones/test.png') }}" /></a>&nbsp;
            &nbsp;<a href="javascript:;" title="supprimer" onclick="javascript:confirm_delete('/personnes/delete/{{ p.id }}')"><img src="{{ url_for('static', filename='icones/supprimer.png') }}" /></a>&nbsp;
          </td>
        </tr>
      {% endfor %}
    {% else %}
      <tr><td colspan="10">Aucune donn&eacute;e!!</td></tr>
    {% endif %}
  </tbody>
</table>